# Generated by Django 3.2 on 2021-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210420_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
